---
- hosts: root
  remote_user: root
  tasks:
    - name: check host network
      ping: 
      register: result

# run "mkpasswd --method=sha-512 work" to get encryptd pwd "work"
    - name: add user:work, if ping is OK
      user: 
        name: work
        password:  '$6$n7PI/8iafV670kDP$XA3q.29JRiFv6BJZ0MjFKMrS5lUVEH8vyr.WV3Xdy5p6MzWTMYvlprfmALkWQZaj1vIn3n6UfWdL2qWxg7Hl7.'
        state: present
        groups:
          - sudo
        shell: /bin/bash
      when: result.ping == "pong"

# now you need to run "ssh-copy-id -i ~/.ssh/id_rsa.pub aliyunwork" against your local machine.
