---
- hosts: panghu
  remote_user: root
  tasks:
    - name: check host network
      ping: 
      register: result

    - name: add user:work, if ping is OK
      user: 
        name: work
        password: work 
        state: present
      when: result.ping == "pong"

    - name: 'install lrzsz for rz order'
      yum:
        name: lrzsz
        state: present

    - name: 'install upzip zip'
      yum:
        name: ['unzip', 'zip']
        state: present

      # 后续就要配置一下ssh免密登录 root 和 work账户都要配置
