---
# ansible-playbook -i inventory/ 01_git.yml -v -K
- hosts: work
  roles:
    - role: geerlingguy.git
      become: yes
      vars:
        # 从源码安装
        git_install_from_source: true
        # 安装最新版本
        git_install_from_source_force_update: true
    
#  environment:
#    http_proxy: http://127.0.0.1:8118
#    https_proxy: http://127.0.0.1:8118
