---
- hosts: root
  become: yes
  tasks:
    - name: install dependences
      package:
        name: ['gettext', 'build-essential', 'autoconf', 'libtool', 'libpcre3-dev', 'asciidoc', 'xmlto', 'libev-dev', 'libc-ares-dev', 'automake','libmbedtls-dev', 'libsodium-dev']
        state: present

    - name: install snap 
      command:
        cmd: "{{ item  }}"
      with_items:
        - apt update
        - apt update
        - apt install -y snapd
        - snap install core
      register: snapresult

    - name: reboot
      shell:
        cmd: sleep 5 && reboot
      async: 1 # timeout for the current task
      poll: 0 #  start the next task immediately
      when: snapresult.changed

    - name: wait for reboot...
      wait_for_connection:
        connect_timeout: 30
        sleep: 5
        delay: 5
        timeout: 1200
      when: snapresult.changed

    - name: shadowsocks-libev
      shell:
        cmd: sleep 5 && snap install shadowsocks-libev


