- name: create pgdata volume
  shell: docker volume create pgdata

- name: install postgres
  docker_container:
    name: postgres
    image: postgres
    state: started
    ports:
      - "5432:5432/tcp"
    volumes:
      - pgdata:/var/lib/postgresql/data

- name: pgcli
  pip:
    name: pgcli
    state: latest
